//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depto
    {
        public decimal IdDepto { get; set; }
        public string descricao { get; set; }
        public decimal IdEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
